### ISSUE TITLE
YouTube video link not working

### ISSUE THREAD

**Issue by RiyasKpkr** [patildarshan66/reels_viewer#4]
E/ExoPlayerImplInternal(25450): Playback error
E/ExoPlayerImplInternal(25450):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(25450):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
E/ExoPlayerImplInternal(25450):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:654)
E/ExoPlayerImplInternal(25450):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(25450):       at android.os.Looper.loopOnce(Looper.java:211)
E/ExoPlayerImplInternal(25450):       at android.os.Looper.loop(Looper.java:300)
E/ExoPlayerImplInternal(25450):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(25450):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.{contentIsMalformed=false, dataType=1}
E/ExoPlayerImplInternal(25450):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:98)
E/ExoPlayerImplInternal(25450):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1025)
E/ExoPlayerImplInternal(25450):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
E/ExoPlayerImplInternal(25450):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/ExoPlayerImplInternal(25450):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/ExoPlayerImplInternal(25450):       at java.lang.Thread.run(Thread.java:1012)
E/flutter (25450): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)

**Comment by patildarshan66** [comment]
@RiyasKpkr will give support for YouTube videos in the next release. Thanks for reporting.
